/* Generated By:JJTree&JavaCC: Do not edit this line. html32Constants.java */
package Connection;

public interface html32Constants {

  int EOF = 0;
  int STAGO = 3;
  int ETAGO = 4;
  int PCDATA = 5;
  int A = 6;
  int ADDRESS = 7;
  int APPLET = 8;
  int AREA = 9;
  int B = 10;
  int BASE = 11;
  int BASEFONT = 12;
  int BIG = 13;
  int BLOCKQUOTE = 14;
  int BODY = 15;
  int BR = 16;
  int CAPTION = 17;
  int CENTER = 18;
  int CITE = 19;
  int CODE = 20;
  int DD = 21;
  int DFN = 22;
  int DIR = 23;
  int DIV = 24;
  int DL = 25;
  int DT = 26;
  int EM = 27;
  int FONT = 28;
  int FORM = 29;
  int H1 = 30;
  int H2 = 31;
  int H3 = 32;
  int H4 = 33;
  int H5 = 34;
  int H6 = 35;
  int HEAD = 36;
  int HR = 37;
  int HTML = 38;
  int I = 39;
  int IMG = 40;
  int INPUT = 41;
  int ISINDEX = 42;
  int KBD = 43;
  int LI = 44;
  int LINK = 45;
  int MAP = 46;
  int MENU = 47;
  int META = 48;
  int OL = 49;
  int OPTION = 50;
  int P = 51;
  int PARAM = 52;
  int PRE = 53;
  int PROMPT = 54;
  int SAMP = 55;
  int SCRIPT = 56;
  int SELECT = 57;
  int SMALL = 58;
  int STRIKE = 59;
  int STRONG = 60;
  int STYLE = 61;
  int SUB = 62;
  int SUP = 63;
  int TABLE = 64;
  int TD = 65;
  int TEXTAREA = 66;
  int TH = 67;
  int TITLE = 68;
  int TR = 69;
  int TT = 70;
  int U = 71;
  int UL = 72;
  int VAR = 73;
  int TAGC = 76;
  int A_EQ = 77;
  int ALPHA = 78;
  int NUM = 79;
  int ALPHANUM = 80;
  int A_NAME = 81;
  int CDATA = 83;

  int DEFAULT = 0;
  int TAG = 1;
  int ATTLIST = 2;
  int ATTRVAL = 3;
  int ATTCOMM = 4;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\"<\"",
    "\"</\"",
    "<PCDATA>",
    "\"a\"",
    "\"address\"",
    "\"applet\"",
    "\"area\"",
    "\"b\"",
    "\"base\"",
    "\"basefont\"",
    "\"big\"",
    "\"blockquote\"",
    "\"body\"",
    "\"br\"",
    "\"caption\"",
    "\"center\"",
    "\"cite\"",
    "\"code\"",
    "\"dd\"",
    "\"dfn\"",
    "\"dir\"",
    "\"div\"",
    "\"dl\"",
    "\"dt\"",
    "\"em\"",
    "\"font\"",
    "\"form\"",
    "\"h1\"",
    "\"h2\"",
    "\"h3\"",
    "\"h4\"",
    "\"h5\"",
    "\"h6\"",
    "\"head\"",
    "\"hr\"",
    "\"html\"",
    "\"i\"",
    "\"img\"",
    "\"input\"",
    "\"isindex\"",
    "\"kbd\"",
    "\"li\"",
    "\"link\"",
    "\"map\"",
    "\"menu\"",
    "\"meta\"",
    "\"ol\"",
    "\"option\"",
    "\"p\"",
    "\"param\"",
    "\"pre\"",
    "\"prompt\"",
    "\"samp\"",
    "\"script\"",
    "\"select\"",
    "\"small\"",
    "\"strike\"",
    "\"strong\"",
    "\"style\"",
    "\"sub\"",
    "\"sup\"",
    "\"table\"",
    "\"td\"",
    "\"textarea\"",
    "\"th\"",
    "\"title\"",
    "\"tr\"",
    "\"tt\"",
    "\"u\"",
    "\"ul\"",
    "\"var\"",
    "<token of kind 74>",
    "\"--\"",
    "\">\"",
    "\"=\"",
    "<ALPHA>",
    "<NUM>",
    "<ALPHANUM>",
    "<A_NAME>",
    "<token of kind 82>",
    "<CDATA>",
    "<token of kind 84>",
    "<token of kind 85>",
    "\"--\"",
  };

}
