/* Generated By:JJTree: Do not edit this line. html32TreeConstants.java */
package Connection;


public interface html32TreeConstants
{
  int JJTVOID = 0;
  int JJTATTLIST = 1;
  int JJTTT = 2;
  int JJTI = 3;
  int JJTB = 4;
  int JJTU = 5;
  int JJTSTRIKE = 6;
  int JJTBIG = 7;
  int JJTSMALL = 8;
  int JJTSUB = 9;
  int JJTSUP = 10;
  int JJTEM = 11;
  int JJTSTRONG = 12;
  int JJTDFN = 13;
  int JJTCODE = 14;
  int JJTSAMP = 15;
  int JJTKBD = 16;
  int JJT_VAR = 17;
  int JJTCITE = 18;
  int JJTFONT = 19;
  int JJTBASEFONT = 20;
  int JJTBR = 21;
  int JJTBODY = 22;
  int JJTADDRESS = 23;
  int JJTDIV = 24;
  int JJTCENTER = 25;
  int JJTA = 26;
  int JJTMAP = 27;
  int JJTAREA = 28;
  int JJTLINK = 29;
  int JJTIMG = 30;
  int JJTAPPLET = 31;
  int JJTPARAM = 32;
  int JJTHR = 33;
  int JJTP = 34;
  int JJTH1 = 35;
  int JJTH2 = 36;
  int JJTH3 = 37;
  int JJTH4 = 38;
  int JJTH5 = 39;
  int JJTH6 = 40;
  int JJTPRE = 41;
  int JJTBLOCKQUOTE = 42;
  int JJTDL = 43;
  int JJTDT = 44;
  int JJTDD = 45;
  int JJTOL = 46;
  int JJTUL = 47;
  int JJTDIR = 48;
  int JJTMENU = 49;
  int JJTLI = 50;
  int JJTFORM = 51;
  int JJTINPUT = 52;
  int JJTSELECT = 53;
  int JJTOPTION = 54;
  int JJTTEXTAREA = 55;
  int JJTTABLE = 56;
  int JJTTR = 57;
  int JJTTH = 58;
  int JJTTD = 59;
  int JJTCAPTION = 60;
  int JJTHEAD = 61;
  int JJTTITLE = 62;
  int JJTISINDEX = 63;
  int JJTBASE = 64;
  int JJTMETA = 65;
  int JJTSTYLE = 66;
  int JJTSCRIPT = 67;
  int JJTHTML = 68;


  String[] jjtNodeName = {
    "void",
    "attlist",
    "tt",
    "i",
    "b",
    "u",
    "strike",
    "big",
    "small",
    "sub",
    "sup",
    "em",
    "strong",
    "dfn",
    "code",
    "samp",
    "kbd",
    "_var",
    "cite",
    "font",
    "basefont",
    "br",
    "body",
    "address",
    "div",
    "center",
    "a",
    "map",
    "area",
    "link",
    "img",
    "applet",
    "param",
    "hr",
    "p",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "pre",
    "blockquote",
    "dl",
    "dt",
    "dd",
    "ol",
    "ul",
    "dir",
    "menu",
    "li",
    "form",
    "input",
    "select",
    "option",
    "textarea",
    "table",
    "tr",
    "th",
    "td",
    "caption",
    "head",
    "title",
    "isindex",
    "base",
    "meta",
    "style",
    "script",
    "html",
  };
}
