#!/bin/sh
#
# @(#)runnit	1.4 97/10/14

#SDKHOME=/nfs/v2/jihie/java/sdk
#SDKHOME=/local/java
SDKHOME=/nfs/etg/apps/java/jdk1.2.2

CLIENTHOME=/nfs/v2/expect/current/clients

# Compute an absolute pathname here because Class.getResource()
# fails if $CLASSPATH contains "../".

#SCLASSPATH=.:classes:/nfs/v2/expect/current/clients:${CLIENTHOME}/EMeD/classes:${CLIENTHOME}/PSMTool/classes:${SDKHOME}/lib/dt.jar:${SDKHOME}/lib/tools.jar:/nfs/v2/jihie/java/XML/xml4j3/xml4j.jar:/nfs/v2/jihie/java/XML/xml4j3/xerces.jar:/nfs/v2/jihie/java/XML/saxon

SCLASSPATH=.:classes:/nfs/v2/expect/current/clients:${CLIENTHOME}/expect.jar:${SDKHOME}/lib/dt.jar:${SDKHOME}/lib/tools.jar:/nfs/v2/jihie/java/XML/xml4j3/xml4j.jar:/nfs/v2/jihie/java/XML/xml4j3/xerces.jar:/nfs/v2/jihie/java/XML/saxon

CLASS=$1

echo "Class is $CLASS"
if (test $CLASS="") ; then CLASS="RKF" ; fi

CMD="${SDKHOME}/bin/java -classpath ${SCLASSPATH} $CLASS"

#CMD="/nfs/etg/apps/java/jdk1.2.2/bin/java -classpath ${SCLASSPATH} PSMTool"

echo ${CMD}
${CMD}
