set CLASSPATH=C:\Mukta\current\clients\EMeD-Mukta\Tree\classes;C:\Mukta\current\clients\all-classes;C:\Mukta\current\clients\EMeD-Mukta\Tree;C:\Mukta\current\clients\EMeD-Mukta\Tree\classes\Connection;C:\mukta\current\clients\Xml\saxon;
set CLASSPATH=%CLASSPATH%;C:\Mukta\current\clients\Xml\xerces.jar
set CLASSPATH=%CLASSPATH%;C:\Mukta\current\clients\Xml\xml4j.jar;C:\Mukta\current\saxon.zip;C:\Mukta\current\Xml
