
set CLASSPATH=C:\Mukta\current\clients\EMeD-Mukta;C:\Mukta\current\clients\EMeD-Mukta\classes;C:\Mukta\current\clients\all-classes;C:\Mukta\current\clients\EMeD-Mukta\Tree;
set CLASSPATH=%CLASSPATH%;C:\Mukta\current\clients\EMeD-Mukta\jaxp.jar;C:\Mukta\current\clients\EMeD-Mukta\classes
set CLASSPATH=%CLASSPATH%;C:\Mukta\current\clients\Xml\saxon; C:\Mukta\current\clients\Xml\xerces.jar
set CLASSPATH=%CLASSPATH%;C:\Mukta\current\clients\Xml\xml4j.jar;C:\Mukta\current\saxon.zip;C:\Mukta\current\Xml
