#!/bin/sh
#
# @(#)runnit	1.4 97/10/14

SDKHOME=/nfs/etg/apps/java/jdk1.2.2
XML=/nfs/v2/expect/current/clients/XML

SCLASSPATH=../expect.jar:../XML/xml4j.jar:../XML/xerces.jar:../XML/saxon

CLASS=$1

echo "Class is $CLASS"
if (test $CLASS="") ; then CLASS="Temple" ; fi

CMD="${SDKHOME}/bin/java -classpath ${SCLASSPATH} $CLASS"


echo ${CMD}
${CMD}

